<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="1" ignored="1" total="7" passed="2" failed="2" skipped="1">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-07-06T13:39:59 IST" name="Suite" finished-at="2024-07-06T13:40:47 IST" duration-ms="48144">
    <groups>
      <group name="ErrorHandling">
        <method signature="ErrorValidationLoginTest.loginErrorValidation()[pri:0, instance:Pranavraj.Test.ErrorValidationLoginTest@3568f9d2]" name="loginErrorValidation" class="Pranavraj.Test.ErrorValidationLoginTest"/>
      </group> <!-- ErrorHandling -->
      <group name="Purchase">
        <method signature="submitorderTest.submitorder(java.util.HashMap)[pri:0, instance:Pranavraj.Test.submitorderTest@ab7395e]" name="submitorder" class="Pranavraj.Test.submitorderTest"/>
      </group> <!-- Purchase -->
    </groups>
    <test started-at="2024-07-06T13:39:59 IST" name="Error Validations Test" finished-at="2024-07-06T13:40:47 IST" duration-ms="47719">
      <class name="Pranavraj.Test.ErrorValidationLoginTest">
        <test-method is-config="true" signature="launchingApplication()[pri:0, instance:Pranavraj.Test.ErrorValidationLoginTest@3568f9d2]" started-at="2024-07-06T13:39:59 IST" name="launchingApplication" finished-at="2024-07-06T13:40:10 IST" duration-ms="10583" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchingApplication -->
        <test-method retried="true" signature="loginErrorValidation()[pri:0, instance:Pranavraj.Test.ErrorValidationLoginTest@3568f9d2]" started-at="2024-07-06T13:40:10 IST" name="loginErrorValidation" finished-at="2024-07-06T13:40:16 IST" duration-ms="5834" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect email or password.] but found [Incorrect email r password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect email or password.] but found [Incorrect email r password.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at Pranavraj.Test.ErrorValidationLoginTest.loginErrorValidation(ErrorValidationLoginTest.java:23)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1570)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginErrorValidation -->
        <test-method is-config="true" signature="quit()[pri:0, instance:Pranavraj.Test.ErrorValidationLoginTest@3568f9d2]" started-at="2024-07-06T13:40:16 IST" name="quit" finished-at="2024-07-06T13:40:16 IST" duration-ms="704" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quit -->
        <test-method is-config="true" signature="launchingApplication()[pri:0, instance:Pranavraj.Test.ErrorValidationLoginTest@3568f9d2]" started-at="2024-07-06T13:40:16 IST" name="launchingApplication" finished-at="2024-07-06T13:40:25 IST" duration-ms="8910" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchingApplication -->
        <test-method signature="loginErrorValidation()[pri:0, instance:Pranavraj.Test.ErrorValidationLoginTest@3568f9d2]" started-at="2024-07-06T13:40:25 IST" name="loginErrorValidation" finished-at="2024-07-06T13:40:28 IST" duration-ms="2482" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect email or password.] but found [Incorrect email r password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect email or password.] but found [Incorrect email r password.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at Pranavraj.Test.ErrorValidationLoginTest.loginErrorValidation(ErrorValidationLoginTest.java:23)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1570)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginErrorValidation -->
        <test-method is-config="true" signature="quit()[pri:0, instance:Pranavraj.Test.ErrorValidationLoginTest@3568f9d2]" started-at="2024-07-06T13:40:29 IST" name="quit" finished-at="2024-07-06T13:40:30 IST" duration-ms="950" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quit -->
        <test-method is-config="true" signature="launchingApplication()[pri:0, instance:Pranavraj.Test.ErrorValidationLoginTest@3568f9d2]" started-at="2024-07-06T13:40:30 IST" name="launchingApplication" finished-at="2024-07-06T13:40:37 IST" duration-ms="7203" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchingApplication -->
        <test-method signature="productErrorValidation()[pri:0, instance:Pranavraj.Test.ErrorValidationLoginTest@3568f9d2]" started-at="2024-07-06T13:40:37 IST" name="productErrorValidation" finished-at="2024-07-06T13:40:46 IST" duration-ms="8623" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- productErrorValidation -->
        <test-method is-config="true" signature="quit()[pri:0, instance:Pranavraj.Test.ErrorValidationLoginTest@3568f9d2]" started-at="2024-07-06T13:40:46 IST" name="quit" finished-at="2024-07-06T13:40:47 IST" duration-ms="1147" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quit -->
      </class> <!-- Pranavraj.Test.ErrorValidationLoginTest -->
    </test> <!-- Error Validations Test -->
    <test started-at="2024-07-06T13:39:59 IST" name="Submit Order Test" finished-at="2024-07-06T13:40:47 IST" duration-ms="48144">
      <class name="Pranavraj.Test.submitorderTest">
        <test-method is-config="true" signature="launchingApplication()[pri:0, instance:Pranavraj.Test.submitorderTest@ab7395e]" started-at="2024-07-06T13:40:00 IST" name="launchingApplication" finished-at="2024-07-06T13:40:09 IST" duration-ms="9823" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchingApplication -->
        <test-method signature="submitorder(java.util.HashMap)[pri:0, instance:Pranavraj.Test.submitorderTest@ab7395e]" started-at="2024-07-06T13:40:09 IST" name="submitorder" data-provider="getData" finished-at="2024-07-06T13:40:26 IST" duration-ms="16703" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=Vtu@12344, product=ZARA COAT 3, email=pranavrajvoola@gmail.com}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitorder -->
        <test-method is-config="true" signature="quit()[pri:0, instance:Pranavraj.Test.submitorderTest@ab7395e]" started-at="2024-07-06T13:40:26 IST" name="quit" finished-at="2024-07-06T13:40:27 IST" duration-ms="877" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quit -->
        <test-method is-config="true" signature="launchingApplication()[pri:0, instance:Pranavraj.Test.submitorderTest@ab7395e]" started-at="2024-07-06T13:40:27 IST" name="launchingApplication" finished-at="2024-07-06T13:40:33 IST" duration-ms="5827" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchingApplication -->
        <test-method signature="submitorder(java.util.HashMap)[pri:0, instance:Pranavraj.Test.submitorderTest@ab7395e]" started-at="2024-07-06T13:40:33 IST" name="submitorder" data-provider="getData" finished-at="2024-07-06T13:40:46 IST" duration-ms="12897" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=Vtu@12344, product=ADIDAS ORIGINAL, email=pranavrajvoola@gmail.com}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at Pranavraj.Test.submitorderTest.submitorder(submitorderTest.java:36)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1570)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitorder -->
        <test-method is-config="true" signature="quit()[pri:0, instance:Pranavraj.Test.submitorderTest@ab7395e]" started-at="2024-07-06T13:40:46 IST" name="quit" finished-at="2024-07-06T13:40:47 IST" duration-ms="1006" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quit -->
        <test-method signature="OrderTest()[pri:0, instance:Pranavraj.Test.submitorderTest@ab7395e]" started-at="2024-07-06T13:40:47 IST" name="OrderTest" finished-at="2024-07-06T13:40:47 IST" depends-on-methods="Pranavraj.Test.submitorderTest.submitorder" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method Pranavraj.Test.submitorderTest.OrderTest() on instance Pranavraj.Test.submitorderTest@ab7395e depends on not successfully finished methods 
[Pranavraj.Test.submitorderTest.submitorder() on instance Pranavraj.Test.submitorderTest@ab7395e]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method Pranavraj.Test.submitorderTest.OrderTest() on instance Pranavraj.Test.submitorderTest@ab7395e depends on not successfully finished methods 
[Pranavraj.Test.submitorderTest.submitorder() on instance Pranavraj.Test.submitorderTest@ab7395e]
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:159)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1570)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- OrderTest -->
      </class> <!-- Pranavraj.Test.submitorderTest -->
    </test> <!-- Submit Order Test -->
  </suite> <!-- Suite -->
</testng-results>
